### PR TITLE
Fixes removedAfterProceeding not dismissing final view when applied to final item in Workflow.

### LINKED ISSUE #19: removedAfterProceeding on last item in Workflow
### Describe the bug
If you have `.removedAfterProceeding` as the `FlowPersistence` on an item in a workflow it does not properly remove that item (UIKit)

## To Reproduce
Create 3 `FlowRepresentable`s the last of which has a `flowPersistence` of `.removedAfterProceeding`
Call `proceedInWorkflow()` on all items in that flow
Observe after OnFinish is called the final `UIViewController` is still displayed

### Expected behavior
The `UIViewController` should not be displayed after the onFinish block has executed

### Screenshots
NO

### PR DESCRIPTION
**Pull request by Richard-Gist**
## Checklist:
- [x] Is the linter reporting 0 errors?
- [x] Did you comply with our [styleguide](https://github.com/wwt/Workflow/blob/main/STYLEGUIDE.md)?
- [ ] Is there [adequate test coverage](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#test-etiquette) for your new code?
- [x] Does the CI pipeline pass?
- [x] Is the [static analysis tool](https://sonarcloud.io/dashboard?id=wwt_Workflow) reporting 0 issues?
- [ ] Did you [update the documentation](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#documentation)?
- [ ] Did you [update the sample app](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#sample-app)?
- [X] Do we need to [increment the minor/major version](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#versioning)?
- [X] Did you [change the public API](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#public-api)?
- [ ] Have you done everything you can to make sure that errors that can occur are compile-time errors, and if they have to be runtime do you have adequate tests and documentation around those runtime errors? [For more details](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#errors).

----

### If Applicable:
- [ ] Did you test when the first item is skipped?
- [ ] Did you test when the last item is skipped?
- [ ] Did you test when middle items are skipped?
- [ ] Did you test when incorrect data is passed forward?
- [ ] Did you test proceeding backwards?

----

### If Public API Has Changed:
- [ ] Did you deprecate (rather than remove) any old methods/variables/etc? [Our philosophy for deprecation](https://github.com/wwt/Workflow/blob/main/CONTRIBUTING.md#deprecation).
- [ ] Have you done the best that you can to make sure that the compiler guides people to changing to the new API? (Example: the renamed attribute)
- [ ] If necessary, have you tested the upgrade path for at least N-1 versions? For example, if data persists between v1 and v2 then that upgrade should be tested and as easy as we can make it.

### CODE REVIEW

**Comment by Richard-Gist** [comment]
This should have been a draft!!

EOD:  We have decided to create a "complete" function on OrchestrationResponder and it will have the sole responsibility of calling the onFinish provided to the Workflow.  In driving out these tests, we decided that the `MockOrchestrationResponder` should have the ability to call a default implementation. In this case, the default is that complete will call onFinish with the passedArgs.

These decisions are being worked through and the current state of the PR is incomplete for all of those decisions.

File: Sources/WorkflowUIKit/UIKitPresenter.swift [hunk 1]
```diff
@@ -61,6 +61,19 @@ open class UIKitPresenter: OrchestrationResponder {
         abandon(workflow, animated: true, onFinish: onFinish)
     }
 
+    public func complete(_ workflow: AnyWorkflow, passedArgs: AnyWorkflow.PassedArgs, onFinish: ((AnyWorkflow.PassedArgs) -> Void)?) {
+        // AnyWorkflow does not have a last(where:)
+        // swiftlint:disable:next last_where
+        let lastInstance = workflow.filter { $0.value.instance != nil }.last
```
Comment (Tyler-Keith-Thompson) [inline Sources/WorkflowUIKit/UIKitPresenter.swift:67]: It wouldn't be hard to add.... Workflow has a last(where:) and you'd just have to call it, exactly like we did to make AnyWorkflow conform to `Sequence`

File: Sources/Workflow/Models/Workflow.swift [hunk 2]
```diff
@@ -191,7 +192,8 @@ public final class Workflow<F: FlowRepresentable>: LinkedList<_WorkflowItem> {
         }
 
         guard let nextNode = nextLoadedNode else {
-            onFinish?(argsToPass)
+            #warning("Workflow in Complete is incorrect. Test Drive it to make it correct.")
+            orchestrationResponder?.complete(AnyWorkflow(Workflow(self.last)), passedArgs: argsToPass, onFinish: onFinish)
```
Comment (Richard-Gist) [inline Sources/Workflow/Models/Workflow.swift:196]: Ok so this is a little odd.  Because I used a node from the linked list the first time, we ended up with a convoluted `AnyWorkflow(self)` which is correct.  Then this code is now actually wrong, BUT it won't fail tests because it still falls under what we are testing (the last item is persisted or not).

So we're still kind of right but really we either need to add tests or finally set it completely right with:
```suggestion
            orchestrationResponder?.complete(AnyWorkflow(self), passedArgs: argsToPass, onFinish: onFinish)
```

File: Sources/WorkflowUIKit/UIKitPresenter.swift (hunk 1 above)
Comment (wiemerm) [reply Sources/WorkflowUIKit/UIKitPresenter.swift]: Did the thing. Happy?

Comment (Tyler-Keith-Thompson) [reply Sources/WorkflowUIKit/UIKitPresenter.swift]: Quite! 🎉

File: Sources/Workflow/Models/Workflow.swift (hunk 2 above)
Comment (wiemerm) [reply Sources/Workflow/Models/Workflow.swift]: We added a test.

**Comment by wiemerm** [comment]
EOD: We addressed existing comments.

**Review by morganzellers — APPROVED** [review]

**Comment by wiemerm** [comment]
EOD:  We continued to drive out changes to the destroy function and handling the onFinish() based on earlier decisions made.

**Review by morganzellers — APPROVED** [review]

File: Tests/WorkflowExampleTests/Mocks/MockOrchestrationResponder.swift [hunk 3]
```diff
@@ -10,6 +10,10 @@ import Foundation
 import Workflow
 
 class MockOrchestrationResponder: OrchestrationResponder {
+    func complete(_ workflow: AnyWorkflow, passedArgs: AnyWorkflow.PassedArgs, onFinish: ((AnyWorkflow.PassedArgs) -> Void)?) {
+
```
Comment (Richard-Gist) [inline Tests/WorkflowExampleTests/Mocks/MockOrchestrationResponder.swift:14]: Needs to be implemented.  Probably should be copied from the other MockOrchestrationResponder.

Comment (wiemerm) [inline Tests/WorkflowExampleTests/Mocks/MockOrchestrationResponder.swift:14]: Needs implementation

File: Tests/WorkflowTests/LinkedListTests.swift [hunk 4]
```diff
@@ -409,6 +409,34 @@ class LinkedListTests: XCTestCase {
         XCTAssertEqual(list.last?.value, 4)
     }
 
+
```
Comment (wiemerm) [inline Tests/WorkflowTests/LinkedListTests.swift:412]: Delete this line; no reason for 2 empty lines here

**Review by Richard-Gist — COMMENTED** [review]
Also, we need to generate new docs for this.

**Review by wiemerm — CHANGES_REQUESTED** [review]

File: Sources/Workflow/Models/Workflow.swift [hunk 5]
```diff
@@ -123,7 +123,7 @@ public final class Workflow<F: FlowRepresentable>: LinkedList<_WorkflowItem> {
         }
 
         guard let first = firstLoadedInstance  else {
-            onFinish?(passedArgs)
+            orchestrationResponder.complete(AnyWorkflow(self), passedArgs: passedArgs, onFinish: onFinish)
```
[the remark this answers is not in the document]
Comment (wiemerm) [reply Sources/Workflow/Models/Workflow.swift:126]: We do have a test that fails by asserting that the complete was called. We could probably add a test to exercise UIKit in this scenario.

File: Sources/Workflow/Protocols/OrchestrationResponder.swift [hunk 6]
```diff
@@ -32,6 +32,13 @@ public protocol OrchestrationResponder {
      - Parameter onFinish: A closure that is executed when the responder is finished abandoning.
      */
     func abandon(_ workflow: AnyWorkflow, onFinish: (() -> Void)?)
+    /**
+     Respond to the `Workflow` completing.
+     - Parameter workflow: The `AnyWorkflow` that is being completed.
+     - Parameter passedArgs: The `AnyWorkflow.PassedArgs` to be passed to `onFinish`.
+     - Parameter onFinish: A closure that is executed when the responder is finished completing.
+     */
+    func complete(_ workflow: AnyWorkflow, passedArgs: AnyWorkflow.PassedArgs, onFinish: ((AnyWorkflow.PassedArgs) -> Void)?)
```
Comment (Richard-Gist) [inline Sources/Workflow/Protocols/OrchestrationResponder.swift:41]: I don't see it as a conversation to resolve so I'm adding here.
1. We need to generate the jazzy docs for this change
2. We need to version ramp the minor version of the app as we are adding Complete to the API.

Comment (morganzellers) [reply Sources/Workflow/Protocols/OrchestrationResponder.swift:41]: I see Release CI has been bumping the patch version on merges to main, how do we increment the minor spot?

File: Sources/Workflow/Models/Workflow.swift (hunk 5 above)
[the remark this answers is not in the document]
Comment (Richard-Gist) [reply Sources/Workflow/Models/Workflow.swift:126]: I have added a test that will cover this for UIKitPresenter.

File: Sources/Workflow/Protocols/OrchestrationResponder.swift (hunk 6 above)
Comment (Richard-Gist) [reply Sources/Workflow/Protocols/OrchestrationResponder.swift:41]: I have version bumped the minor with `bundle exec fastlane minor`

File: Sources/WorkflowUIKit/UIKitPresenter.swift [hunk 7]
```diff
@@ -89,12 +101,21 @@ open class UIKitPresenter: OrchestrationResponder {
...
+    private func destroy(_ view: UIViewController, completion: (() -> Void)? = nil) {
         if let nav = view.navigationController {
             let vcs = nav.viewControllers.filter {
                 $0 !== view
             }
-            nav.setViewControllers(vcs, animated: false)
+
+            if vcs.isEmpty && nav === internalNavigationController {
+                nav.presentingViewController?.dismiss(animated: false) { [weak self] in
+                    self?.internalNavigationController?.setViewControllers(vcs, animated: false)
```
[the remark this answers is not in the document]
Comment (Richard-Gist) [reply Sources/WorkflowUIKit/UIKitPresenter.swift:112]: Yes this line needs it and I don't know how to test..... I'll share with the class tomorrow.

[the remark this answers is not in the document]
Comment (Richard-Gist) [reply Sources/WorkflowUIKit/UIKitPresenter.swift]: Actually, I'm full of lies and that line is not needed and I was just needing to give it more time to cleanup.  No leak here.

**Review by wiemerm — DISMISSED** [review]

**Comment by wiemerm** [comment]
Good to merge after the docs are updated.

File: Sources/Workflow/Protocols/OrchestrationResponder.swift (hunk 6 above)
Comment (Richard-Gist) [reply Sources/Workflow/Protocols/OrchestrationResponder.swift:41]: Last commit generated the docs and added some more.

**Review by wiemerm — APPROVED** [review]

**Review by morganzellers — APPROVED** [review]
